"""Initial migration with customer table

Revision ID: 6309af6ab3df
Revises: 
Create Date: 2025-08-30 12:56:36.974011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6309af6ab3df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_ticket_inventory',
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], ),
    sa.PrimaryKeyConstraint('service_ticket_id', 'inventory_id')
    )
    op.create_table('service_ticket_mechanic',
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], ),
    sa.PrimaryKeyConstraint('service_ticket_id', 'mechanic_id')
    )
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('service_ticket_mechanic')
    op.drop_table('service_ticket_inventory')
    # ### end Alembic commands ###
