"""Add mechanic table

Revision ID: ec0a3c3118f6
Revises: 95714d666ca4
Create Date: 2025-08-29 15:36:53.341390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec0a3c3118f6'
down_revision = '95714d666ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop association tables first to avoid foreign key errors
    op.drop_table('service_ticket_mechanic')
    op.drop_table('service_ticket_inventory')

    # Now drop referenced tables and indexes
    #with op.batch_alter_table('mechanic', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('email'))
        #batch_op.drop_index(batch_op.f('username'))
    op.drop_table('mechanic')

    #with op.batch_alter_table('inventory', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('name'))
    op.drop_table('inventory')

    #with op.batch_alter_table('admin', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('email'))
        #batch_op.drop_index(batch_op.f('username'))
    #op.drop_table('admin')

    op.drop_table('service_ticket')

    #with op.batch_alter_table('customer', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('email'))
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('service_ticket',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('vehicle_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('hours_worked', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repair', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='service_ticket_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('service_ticket_mechanic',
    sa.Column('service_ticket_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mechanic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], name=op.f('service_ticket_mechanic_ibfk_1')),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], name=op.f('service_ticket_mechanic_ibfk_2')),
    sa.PrimaryKeyConstraint('service_ticket_id', 'mechanic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
#    op.create_table('admin',
#    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
#    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
#    sa.Column('username', mysql.VARCHAR(length=150), nullable=False),
#    sa.Column('password', mysql.VARCHAR(length=250), nullable=False),
#    sa.Column('email', mysql.VARCHAR(length=300), nullable=True),
#    sa.Column('address', mysql.VARCHAR(length=250), nullable=True),
#    sa.PrimaryKeyConstraint('id'),
#    mysql_collate='utf8mb4_0900_ai_ci',
#    mysql_default_charset='utf8mb4',
#    mysql_engine='InnoDB'
#    )
#    with op.batch_alter_table('admin', schema=None) as batch_op:
#        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
#        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('service_ticket_inventory',
    sa.Column('service_ticket_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventory_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('service_ticket_inventory_ibfk_1')),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], name=op.f('service_ticket_inventory_ibfk_2')),
    sa.PrimaryKeyConstraint('service_ticket_id', 'inventory_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inventory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('mechanic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('phone', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hours_worked', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('specialty', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
