name: Mechanic_Shop

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          FLASK_ENV: testing
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
        run: |
          flask db upgrade

      - name: Run unit tests
        env:
          FLASK_ENV: testing
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
        run: |
          python -m unittest discover tests

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          FLASK_ENV: production
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
        run: |
          flask db upgrade

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}